### ISSUE TITLE
Arrow shapes are not exported to DOT

### ISSUE THREAD

**Issue by keiono** [idekerlab/dot-app#2]
Arrow shapes are not exported if they are set as Default.

Maybe this code helps to fix this issue:

https://github.com/cytoscape/cytoscape-impl/blob/develop/json-impl/src/main/java/org/cytoscape/io/internal/write/json/serializer/CytoscapeJsVisualStyleSerializer.java

**Comment by massoudTheDude** [comment]
We are aware of this issue. It only applies to default target/head arrow shapes, not with default source/tail arrow shapes. We think it is because of an minor mistake in the source code here:

https://github.com/cytoscape/cytoscape-impl/blob/develop/ding-impl/ding-presentation-impl/src/main/java/org/cytoscape/ding/impl/DEdgeDetails.java 

We think the error is on line 367. Compare it with the similar method on line 275.
